name: Publish to npm

on:

  push:
    tags: 
      - 'v*.*.*'
jobs:
  build:
    # 指定操作系统为'ubuntu-latest'
    runs-on: ubuntu-latest
    steps:
      # 检查仓库以便作业能正常访问
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      # npm ci命令类似于 npm install 但它旨在用于自动化环境，如测试平台，持续集成和部署
      # 可以帮助捕获由大多数 npm 用户的增量安装的本地环境引起的错误或不一致
      - run: npm ci
      # 发布命令
      - run: npm publish
        env:
          # npm_token 就是刚刚填写 token 时取的名字
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
